language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm install $TYPESCRIPT
  - npm run test

env:
  - TYPESCRIPT=typescript@1.8
  - TYPESCRIPT=typescript@latest
  - TYPESCRIPT=typescript@next

node_js:
  - "stable"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
